### ISSUE TITLE
build: publish Murmur for Vue 3 on NPM

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/murmur#84]

**Comment by caro3801** [comment]
- Murmur next is published as version 4.0.0 of murmur on npm
- Use of github action to install, test, build storybook and deploy on github page 

To fix with deeper understanding of Vue3:
- Maps annotations are not working 
- Range picker basic visualisation has a weird container behavior.
- Symbol map are not working
- Dark mode is not fixed on all composants
